### ISSUE TITLE
Crash when using multiple lines as location.

### ISSUE THREAD

**Issue by SE7-KN8** [thellmund/Android-Week-View#103]
**Describe the bug**
WeekView crashes when Event contains linebreak in the location variable

**Stacktrace**
```java
    java.lang.IllegalStateException: Check failed.
        at com.alamkanak.weekview.TextFitter.toPair(TextFitter.kt:119)
        at com.alamkanak.weekview.TextFitter.replaceNewLineWithSpace(TextFitter.kt:78)
        at com.alamkanak.weekview.TextFitter.fit(TextFitter.kt:32)
        at com.alamkanak.weekview.EventChipDrawer.calculateTextHeightAndDrawTitle(EventChipDrawer.kt:183)
        at com.alamkanak.weekview.EventChipDrawer.draw$core_release(EventChipDrawer.kt:58)
        at com.alamkanak.weekview.EventChipDrawer.draw$core_release$default(EventChipDrawer.kt:29)
        at com.alamkanak.weekview.SingleEventsDrawer.drawEventsForDate(EventsDrawers.kt:32)
        at com.alamkanak.weekview.SingleEventsDrawer.draw(EventsDrawers.kt:21)
        at com.alamkanak.weekview.WeekView.performDrawing(WeekView.kt:102)
        at com.alamkanak.weekview.WeekView.onDraw(WeekView.kt:76)
        at android.view.View.draw(View.java:20495)
        at android.view.View.updateDisplayListIfDirty(View.java:19306)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
        at android.view.View.updateDisplayListIfDirty(View.java:19266)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
        at android.view.View.updateDisplayListIfDirty(View.java:19266)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
        at android.view.View.updateDisplayListIfDirty(View.java:19266)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
        at android.view.View.updateDisplayListIfDirty(View.java:19266)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
        at android.view.View.updateDisplayListIfDirty(View.java:19266)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
        at android.view.View.updateDisplayListIfDirty(View.java:19266)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
        at android.view.View.updateDisplayListIfDirty(View.java:19266)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
        at android.view.View.updateDisplayListIfDirty(View.java:19266)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:740)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:746)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:861)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3586)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3382)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2714)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
        at android.view.Choreographer.doCallbacks(Choreographer.java:893)
        at android.view.Choreographer.doFrame(Choreographer.java:812)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7593)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**To Reproduce**
1. Add an event with a newline character '\n' in the location

**Expected behavior**
Instead of crashling it should render the linebreak or ignore the linebreak.

**Additional context**
 - Android version: Android 9
 - WeekView version: current master branch

**Comment by thellmund** [comment]
Thanks for reporting this, @SE7-KN8. I have fixed the issue (6226ae0c284517bc6c37b545c4af11d5e7f35f9f). Line breaks in both title and location will be preserved.
